server:
  address: 0.0.0.0
  port: 8080
spring:
  data:
    redis:
      host: 47.102.40.253
      port: 6379
  datasource:
    url: jdbc:mysql://47.102.40.253:3306/agent_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: crm114514
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.rna.agentservice.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: qwen-plus-2025-07-28
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${API-KEY}
      model-name: qwen-plus-2025-07-28
      log-requests: true
      log-responses: true
  community:
    redis:
      host: 47.102.40.253
      port: 6379
      dimension: 384

logging:
  level:
    dev.langchain4j: debug


